project:
  type: website
  output-dir: docs

website:
  title: "seoyeon-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/9-1333/seoyeon-blog
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



